services:
  postgres:
    image: postgres:15.0-alpine
    container_name: todo-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres:
