services:
  todo:
    build: .
    image: todo:1.0.0
    container_name: todo
    command: >
      bash -c "npx typeorm migration:run -d dist/dataSource.js
      && npm start"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.0-alpine
    container_name: todo-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres:
